version: '3.8'

services:
  # PostgreSQL with PostGIS for spatial data
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: cholera_ew
      POSTGRES_USER: cholera_user
      POSTGRES_PASSWORD: cholera_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cholera_user -d cholera_ew"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and task queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # MLflow tracking server
  mlflow:
    image: python:3.11-slim
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - mlflow_artifacts:/mlflow/artifacts
    working_dir: /app
    command: >
      bash -c "
        pip install mlflow psycopg2-binary &&
        mlflow server --backend-store-uri postgresql://cholera_user:cholera_password@postgres:5432/cholera_ew 
        --default-artifact-root /mlflow/artifacts 
        --host 0.0.0.0 
        --port 5000
      "
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://cholera_user:cholera_password@postgres:5432/cholera_ew

  # FastAPI backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgresql://cholera_user:cholera_password@postgres:5432/cholera_ew
      - REDIS_URL=redis://redis:6379
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - PYTHONPATH=/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      mlflow:
        condition: service_started
    command: >
      bash -c "
        pip install -r requirements.txt &&
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  # Frontend (Dash/Plotly)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    command: >
      bash -c "
        pip install -r requirements.txt &&
        python app.py
      "

  # Prefect server for workflow orchestration
  prefect:
    image: prefecthq/prefect:2-python3.11
    ports:
      - "4200:4200"
    volumes:
      - ./backend:/app
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql://cholera_user:cholera_password@postgres:5432/cholera_ew
      - PREFECT_API_URL=http://prefect:4200/api
    command: >
      bash -c "
        prefect server start --host 0.0.0.0 --port 4200
      "
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  mlflow_artifacts: